# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "mailserver" do |config|
        config.vm.box      = "ubuntu/trusty64"
        config.vm.hostname = "mailserver"

        config.vm.network :private_network, ip: "192.168.56.31"
        config.vm.network :forwarded_port, guest: 444, host: 444 # Pass through for mailadmin

        config.vm.synced_folder "../files", "/etc/puppet/files"
        config.vm.synced_folder "../", "/setup/root"

        config.ssh.forward_agent = true

        config.vm.provider :virtualbox do |vb|
            vb.name   = config.vm.hostname
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            vb.gui = false
        end

        config.vm.provision "shell", inline: "sh /setup/root/install_puppet.sh"

        config.vm.provision :puppet,
            :facter => {
                "fqdn"    => config.vm.hostname,
                "vm_type" => "vagrant",
            } do |puppet|
                puppet.manifests_path = "../manifests"
                puppet.module_path    = "../modules"
                puppet.manifest_file  = "main.pp"
                #puppet.options        = "--verbose --debug"
            end
    end

end
